# Generated by Django 5.1.2 on 2024-10-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bankoffers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankoffer",
            name="offer_details_url",
            field=models.URLField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
