# Generated by Django 5.1.2 on 2024-10-16 21:41

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "userid",
                    models.CharField(
                        default=users.models.gen_uuid4_userid,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phonenumber", models.CharField(max_length=12, unique=True)),
                ("education_level", models.CharField(max_length=32)),
                ("income_level", models.CharField(max_length=32)),
                ("skills", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
